name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: public_html/
        # Evita subir a pasta do git, os arquivos do github actions e os scripts geradores
        exclude: |
          **/.git*
          **/.git*/**
          **/.github/**
          generator.py
          generate_pages.ps1
